// Generated by CoffeeScript 1.10.0
(function() {
  "use strict";
  (function($) {
    var Sidebar;
    Sidebar = function(element, options) {
      this.option = options;
      this.$body = $(document.body);
      this.$element = $(element);
      return this.isShown = false;
    };
    Sidebar.DEFAULTS = {};
    Sidebar.prototype.toggle = function(_relativeTarget) {
      if (this.isShown) {
        return this.hide();
      } else {
        return this.show(_relativeTarget);
      }
    };
    Sidebar.prototype.show = function(_relativeTarget) {
      var that;
      that = this;
      if (this.isShown) {
        0;
      }
      return this.isShown = true;
    };
    return console.log("end");
  })(window.jQuery);

}).call(this);
